name: GuguSlimefunLib
version: '${project.version}'
main: me.ddggdd135.guguslimefunlib.GuguSlimefunLib
api-version: '1.16'
authors:
  - JWJUN233233
depend:
  - Slimefun

commands:
  server_uuid:
    description: "获取服务器uuid"

permissions:
  guguslimefunlib.server_uuid:
    description: "获取服务器uuid"
    default: op